version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/user_db
      MYSQL_ROOT_PASSWORD: Root123456  # Set a specific password for the root user
      TZ: "UTC"  # Set the timezone to UTC
    ports:
      - '3307:3306'
